<?php

namespace App\Filament\Resources\ReportSnapshots\Tables;

use App\Actions\Documents\RenderDocument;
use App\Actions\Reports\GenerateScopedReport;
use App\Enums\ReportSnapshotScope;
use App\Models\ReportSnapshot;
use App\Models\User;
use Filament\Actions\Action;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Storage;

class ReportSnapshotsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('scope')->badge()->searchable(),
                TextColumn::make('generatedBy.name')
                    ->label('Generated by')
                    ->searchable(),
                TextColumn::make('metrics.bookings_total')
                    ->label('Bookings')
                    ->sortable(),
                TextColumn::make('metrics.open_disputes')
                    ->label('Open disputes')
                    ->sortable(),
                TextColumn::make('metrics.pending_payouts')
                    ->label('Pending payouts')
                    ->sortable(),
                TextColumn::make('generated_at')->dateTime()->sortable(),
            ])
            ->filters([
                SelectFilter::make('scope')->options(ReportSnapshotScope::class),
            ])
            ->headerActions([
                self::generateAction(),
            ])
            ->recordActions([
                ViewAction::make(),
                self::renderAction(),
            ])
            ->defaultSort('generated_at', 'desc');
    }

    private static function generateAction(): Action
    {
        return Action::make('generateReport')
            ->label('Generate report')
            ->action(function (): void {
                /** @var User $actor */
                $actor = auth()->user();
                app(GenerateScopedReport::class)->handle($actor);
            });
    }

    private static function renderAction(): Action
    {
        return Action::make('renderDocument')
            ->label('Render PDF')
            ->action(function (ReportSnapshot $record): void {
                Storage::makeDirectory('reports');
                $path = Storage::path('reports/report-'.$record->id.'.pdf');

                app(RenderDocument::class)->handle('documents.report', ['snapshot' => $record], $path);
            });
    }
}
