<?php

namespace App\Filament\Resources\ReportSnapshots\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ReportSnapshotInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('scope')->badge(),
                TextEntry::make('generatedBy.name')->label('Generated by')->placeholder('-'),
                TextEntry::make('period_start')->date()->placeholder('-'),
                TextEntry::make('period_end')->date()->placeholder('-'),
                TextEntry::make('generated_at')->dateTime(),
                TextEntry::make('metrics')
                    ->formatStateUsing(fn (mixed $state): string => json_encode($state, JSON_PRETTY_PRINT) ?: '')
                    ->columnSpanFull(),
            ]);
    }
}
